version: "3"
services:
  php-dev:
    image: sptr/hospital/php-dev-core:latest
    environment:
      - XDEBUG_CONFIG="remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT}"
    container_name: ${COMPOSE_PROJECT_NAME}-php-dev
    hostname: ${COMPOSE_PROJECT_NAME}-php-dev
    restart: always
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    ports:
      - "8000:8000"  
  postgres:
    image: postgres:10-alpine
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 35432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - all
#      - default  

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  postgres_data:
    driver: local